tap 'homebrew/cask-fonts'


# missing 
# oh-my-zsh

# o365
# ms remote desktop 
# vault


brew 'bash'

brew 'zsh'
brew 'zsh-completions'

brew 'shellcheck'
brew 'bats-core'
brew 'ssh-copy-id'
brew 'watch'
brew 'wget'
brew 'curl'
brew 'htop'

# whiptail
brew "newt"

brew 'tmux'
brew 'tmuxinator'    

brew 'git'
brew 'gh'
brew 'git-extras'
brew 'gpg'

brew 'imagemagick'

brew 'jq'
brew 'yq'

brew 'dive'
brew 'container-diff'
brew 'container-structure-test'

brew 'awscli'
brew 'aws-okta'

brew 'tfenv'
brew 'terraform-docs'
brew 'checkov'
brew 'terraform_landscape'

brew 'kubectx'
brew 'skaffold'
brew 'kubernetes-cli'
brew 'kind'
brew 'kubernetes-helm'
#brew 'kuttl-cli'

brew 'pyenv'
brew 'pipenv'

brew 'nvm'
brew 'circleci'
brew 'nmap'
brew 'youtube-dl'
brew 'gomplate'

brew 'ansible'
brew 'ffmpeg'

# Apps
cask '1password'
cask 'docker'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'google-chrome'
cask 'iterm2'
cask 'font-hack-nerd-font'
cask 'keepassx'
cask 'keybase' 
cask 'homebrew/cask/docker'
cask 'google-chrome'
cask 'iterm2'
cask 'spectacle'
cask 'vagrant'
cask 'vlc'
cask 'hex-fiend'
cask 'slack'
cask 'spotify'
cask 'discord'
cask 'pritunl'
cask 'visual-studio-code'
cask 'sketchbook'
cask 'onedrive'
cask 'microsoft-remote-desktop'
cask 'zoom'
