#!/usr/bin/env bash
set -euf -o pipefail

readonly SCRIPT_NAME=$(basename "$0")
readonly SCRIPT_PATH=${0}
# shellcheck disable=SC2034
readonly SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

${SCRIPT_DIR}/../vscode/vscode-workspaces.sh --profile-dir=${SCRIPT_DIR}/../vscode $@