--- 

- name: Clone dotfiles
  git:
    repo: 'https://github.com/chrisguest75/default_dotfiles.git'
    dest: /home/{{ install_user }}/Code/default_dotfiles
  become_user: "{{ install_user }}"

- name: Get git revision
  shell: | 
    git rev-parse HEAD
    git show HEAD -q 

  args:
    chdir: "/home/{{ install_user }}/Code/default_dotfiles"
  register: git_revision_out
  become_user: "{{ install_user }}"

- name: Print git revision
  debug:
    msg: '{% for line in git_revision_out.stdout_lines %}{{ line }}/n 
          {% endfor %}'      

- name: Install dotfiles
  shell: "./install.sh"
  args:
    chdir: "/home/{{ install_user }}/Code/default_dotfiles"  
  become_user: "{{ install_user }}"
  register: dotfiles_install_out

- name: Dotfile install output
  debug:
    msg: '{% for line in dotfiles_install_out.stdout_lines %}{{ line }}/n 
          {% endfor %}'    


