---

- name: get hostname
  shell: hostname
  register: hostname

- name: apt install basics
  apt: 
    pkg:
      - curl 
      - git 
      - zsh
      - nano
      - bash-completion
      - nmap
      - shellcheck
      - curl
      - tmuxinator
      - jq
      - hub
      - keepassx
      - vim 

  become: True
  #become_user: "{{ install_user }}"

#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist

