# provision.yml

- name: Provision machines
  hosts: "all"
  gather_facts: yes
  # vars:
  #   ansible_become_pass: ""  

  pre_tasks:
    - name: get hostname
      shell: hostname
      register: hostname_out

    - debug:
        var: hostname_out.stdout

    - name: host os
      shell: |
        lsb_release -a 
        uname -a 
      register: hostos_out

    - debug:
        var: hostos_out.stdout
  
    - name: check if .zshrc already exists
      stat:
        path: /home/{{ install_user }}/.zshrc
      register: zshrc_file

    - debug:
        msg: ".zshrc file exists"
      when: zshrc_file.stat.exists

  roles:
    - role: "basic"

    # Do not run this if .zshrc already exsits as it replaces it. 
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ install_user }}"
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git  
      when: not zshrc_file.stat.exists

    # - role: aeimer.install-virtualbox-vagrant      
    #   vars:
    #     virtualbox_version: 6.1
        
    # - role: geerlingguy.docker
    #   vars:
    #     docker_edition: "ce"
    #   when: docker_install == "True"   
    #   become: True

    # - role: "nickjj.docker"
    #   tags: ["docker"]
    #   vars:
    #     docker__edition: "ce"
    #     docker__channel: ["stable"]
    #     docker__version: "19.03.6"
    #     #docker__version: "18.06.1"
    #   when: docker_install == "True"   
    #   become: True

    - role: "dotfiles"
      when: dotfiles_install == "True"   

    - role: "snaps"
      when: snaps_install == "True"  

    - role: "gnome"
      when: gnome_install == "True" 
      