# provision.yml

- name: Provision machines
  hosts: "all"
  gather_facts: yes
  
  roles:
    - role: "basic"

    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ install_user }}"
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git  

    # - role: "nickjj.docker"
    #   tags: ["docker"]
    #   vars:
    #     docker__edition: "ce"
    #     docker__channel: ["stable"]
    #     docker__version: "19.03.6"
    #     #docker__version: "18.06.1"
    #   when: docker_install == "True"   
    #   become: True

    - role: "dotfiles"
      when: dotfiles_install == "True"  
